/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppActionItemsRouteImport } from './routes/app.action-items'
import { Route as AppKnowledgeRouteImport } from './routes/app.knowledge'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppMeetingsIndexRouteImport } from './routes/app.meetings.index'
import { Route as AppMeetingsIdRouteImport } from './routes/app.meetings.$id'
import { Route as AppMeetingsNewRouteImport } from './routes/app.meetings.new'
import { Route as AppOrganizationsIndexRouteImport } from './routes/app.organizations.index'
import { Route as AppOrganizationsIdRouteImport } from './routes/app.organizations.$id'
import { Route as AppParticipantsIdRouteImport } from './routes/app.participants.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppActionItemsRoute = AppActionItemsRouteImport.update({
  id: '/action-items',
  path: '/action-items',
  getParentRoute: () => AppRoute,
} as any)
const AppKnowledgeRoute = AppKnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppMeetingsIndexRoute = AppMeetingsIndexRouteImport.update({
  id: '/meetings/',
  path: '/meetings/',
  getParentRoute: () => AppRoute,
} as any)
const AppMeetingsIdRoute = AppMeetingsIdRouteImport.update({
  id: '/meetings/$id',
  path: '/meetings/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppMeetingsNewRoute = AppMeetingsNewRouteImport.update({
  id: '/meetings/new',
  path: '/meetings/new',
  getParentRoute: () => AppRoute,
} as any)
const AppOrganizationsIndexRoute = AppOrganizationsIndexRouteImport.update({
  id: '/organizations/',
  path: '/organizations/',
  getParentRoute: () => AppRoute,
} as any)
const AppOrganizationsIdRoute = AppOrganizationsIdRouteImport.update({
  id: '/organizations/$id',
  path: '/organizations/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppParticipantsIdRoute = AppParticipantsIdRouteImport.update({
  id: '/participants/$id',
  path: '/participants/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/products': typeof ProductsRoute
  '/register': typeof RegisterRoute
  '/app/action-items': typeof AppActionItemsRoute
  '/app/knowledge': typeof AppKnowledgeRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/': typeof AppIndexRoute
  '/app/meetings/$id': typeof AppMeetingsIdRoute
  '/app/meetings/new': typeof AppMeetingsNewRoute
  '/app/organizations/$id': typeof AppOrganizationsIdRoute
  '/app/participants/$id': typeof AppParticipantsIdRoute
  '/app/meetings/': typeof AppMeetingsIndexRoute
  '/app/organizations/': typeof AppOrganizationsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/products': typeof ProductsRoute
  '/register': typeof RegisterRoute
  '/app/action-items': typeof AppActionItemsRoute
  '/app/knowledge': typeof AppKnowledgeRoute
  '/app/settings': typeof AppSettingsRoute
  '/app': typeof AppIndexRoute
  '/app/meetings/$id': typeof AppMeetingsIdRoute
  '/app/meetings/new': typeof AppMeetingsNewRoute
  '/app/organizations/$id': typeof AppOrganizationsIdRoute
  '/app/participants/$id': typeof AppParticipantsIdRoute
  '/app/meetings': typeof AppMeetingsIndexRoute
  '/app/organizations': typeof AppOrganizationsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/products': typeof ProductsRoute
  '/register': typeof RegisterRoute
  '/app/action-items': typeof AppActionItemsRoute
  '/app/knowledge': typeof AppKnowledgeRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/': typeof AppIndexRoute
  '/app/meetings/$id': typeof AppMeetingsIdRoute
  '/app/meetings/new': typeof AppMeetingsNewRoute
  '/app/organizations/$id': typeof AppOrganizationsIdRoute
  '/app/participants/$id': typeof AppParticipantsIdRoute
  '/app/meetings/': typeof AppMeetingsIndexRoute
  '/app/organizations/': typeof AppOrganizationsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/pricing'
    | '/products'
    | '/register'
    | '/app/action-items'
    | '/app/knowledge'
    | '/app/settings'
    | '/app/'
    | '/app/meetings/$id'
    | '/app/meetings/new'
    | '/app/organizations/$id'
    | '/app/participants/$id'
    | '/app/meetings/'
    | '/app/organizations/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/pricing'
    | '/products'
    | '/register'
    | '/app/action-items'
    | '/app/knowledge'
    | '/app/settings'
    | '/app'
    | '/app/meetings/$id'
    | '/app/meetings/new'
    | '/app/organizations/$id'
    | '/app/participants/$id'
    | '/app/meetings'
    | '/app/organizations'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/login'
    | '/pricing'
    | '/products'
    | '/register'
    | '/app/action-items'
    | '/app/knowledge'
    | '/app/settings'
    | '/app/'
    | '/app/meetings/$id'
    | '/app/meetings/new'
    | '/app/organizations/$id'
    | '/app/participants/$id'
    | '/app/meetings/'
    | '/app/organizations/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  PricingRoute: typeof PricingRoute
  ProductsRoute: typeof ProductsRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/action-items': {
      id: '/app/action-items'
      path: '/action-items'
      fullPath: '/app/action-items'
      preLoaderRoute: typeof AppActionItemsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/knowledge': {
      id: '/app/knowledge'
      path: '/knowledge'
      fullPath: '/app/knowledge'
      preLoaderRoute: typeof AppKnowledgeRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/meetings/': {
      id: '/app/meetings/'
      path: '/meetings'
      fullPath: '/app/meetings/'
      preLoaderRoute: typeof AppMeetingsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/meetings/$id': {
      id: '/app/meetings/$id'
      path: '/meetings/$id'
      fullPath: '/app/meetings/$id'
      preLoaderRoute: typeof AppMeetingsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/meetings/new': {
      id: '/app/meetings/new'
      path: '/meetings/new'
      fullPath: '/app/meetings/new'
      preLoaderRoute: typeof AppMeetingsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/organizations/': {
      id: '/app/organizations/'
      path: '/organizations'
      fullPath: '/app/organizations/'
      preLoaderRoute: typeof AppOrganizationsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/organizations/$id': {
      id: '/app/organizations/$id'
      path: '/organizations/$id'
      fullPath: '/app/organizations/$id'
      preLoaderRoute: typeof AppOrganizationsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/participants/$id': {
      id: '/app/participants/$id'
      path: '/participants/$id'
      fullPath: '/app/participants/$id'
      preLoaderRoute: typeof AppParticipantsIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppActionItemsRoute: typeof AppActionItemsRoute
  AppKnowledgeRoute: typeof AppKnowledgeRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppIndexRoute: typeof AppIndexRoute
  AppMeetingsIdRoute: typeof AppMeetingsIdRoute
  AppMeetingsNewRoute: typeof AppMeetingsNewRoute
  AppOrganizationsIdRoute: typeof AppOrganizationsIdRoute
  AppParticipantsIdRoute: typeof AppParticipantsIdRoute
  AppMeetingsIndexRoute: typeof AppMeetingsIndexRoute
  AppOrganizationsIndexRoute: typeof AppOrganizationsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppActionItemsRoute: AppActionItemsRoute,
  AppKnowledgeRoute: AppKnowledgeRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppIndexRoute: AppIndexRoute,
  AppMeetingsIdRoute: AppMeetingsIdRoute,
  AppMeetingsNewRoute: AppMeetingsNewRoute,
  AppOrganizationsIdRoute: AppOrganizationsIdRoute,
  AppParticipantsIdRoute: AppParticipantsIdRoute,
  AppMeetingsIndexRoute: AppMeetingsIndexRoute,
  AppOrganizationsIndexRoute: AppOrganizationsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  PricingRoute: PricingRoute,
  ProductsRoute: ProductsRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
